kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
        cloud-provider: "external"
        v: "5"
    controllerManager:
      extraArgs:
        cloud-provider: "external"
        v: "5"
    ---
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        cloud-provider: "external"
    ---
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        cloud-provider: "external"
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
    listenAddress: "127.0.0.1"
  - containerPort: 443
    hostPort: 443
    protocol: TCP
    listenAddress: "127.0.0.1"
