apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio-operator

resources:
- github.com/minio/operator?ref=v6.0.4

replicas:
- name: minio-operator
  count: 1

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: minio-operator
      spec:
        template:
          spec:
            containers:
              - name: minio-operator
                env:
                  - name: OPERATOR_STS_ENABLED
                    value: "false"
    target:
      kind: Deployment
      name: minio-operator
